// <auto-generated />
using System;
using AspNetCoreApp.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreApp.Migrations
{
    [DbContext(typeof(RH))]
    [Migration("20200205165107_RH6")]
    partial class RH6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreApp.Models.DB.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("DEPARTAMENTO");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.DB.Empregado", b =>
                {
                    b.Property<int>("Cpf")
                        .HasColumnType("int");

                    b.Property<int?>("CpfSupervisor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("NomeDoMeio")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<int?>("NroDepartamento")
                        .HasColumnType("int");

                    b.Property<decimal>("Salario")
                        .HasColumnType("numeric");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Cpf");

                    b.HasIndex("NroDepartamento");

                    b.ToTable("EMPREGADO");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.DB.Empregado", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.DB.Departamento", "Depart")
                        .WithMany("Empregados")
                        .HasForeignKey("NroDepartamento");
                });
#pragma warning restore 612, 618
        }
    }
}
